### PR TITLE
Finished get_html

### PR DESCRIPTION
**Pull request by armsnyder**
please merge thx

### CODE REVIEW

**Comment by nakfoury** [comment]
Hi Flame,

I really like what you've done here. Specifying a default Application Layer Protocol (HTTP) will save us a lot of time in the long run. As it is the most popular Application Layer Protocol out there, I believe you made a wise decision.

However, I am having some trouble understanding your choice of test case. In the real world, most URLs will be passed to your function WITH an Application Layer Protocol already specified. As such, I would have liked to see a test case for that situation. I'm sorry, but I cannot in good conscience approve your pull request with the test cases the way they are; it is simply inadequate for our purposes here at EECS 337.

Thank you, as always, for your hard work and dedication, and I look forward to reviewing your revised pull request.

Best,
Zinger

**Comment by armsnyder** [comment]
Thank you Zinger for your thorough review of my work here. I will add more test cases as requested and make the code more robust. In the future I will place more focus on test-driven development so that incidents like this do not occur.

Regards,
Flame

**Comment by armsnyder** [comment]
@nakfoury I have made the changes that you so tactfully requested. Would you find it within yourself to give me a second chance on this pull request?

**Comment by nakfoury** [comment]
Flame,

While the work you have done here is certainly improved from your previous request (which, frankly, was made prematurely), what I will certainly NOT tolerate is the flip attitude displayed by your intervening comments. We are enrolled in a SERIOUS CLASS, and I expect nothing but SERIOUS CONTRIBUTIONS from you, both in CODE and in CONVERSATION. The purpose of GitHub is to foster a synergistic work environment for the benefit of the project. In the future, adverbs such as "tactfully" will not be tolerated.

Best,
Zinger

**Comment by armsnyder** [comment]
Oh dear

**Pull request merged**
